knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:    
            page-size: A4
            margin-top: 15mm
            margin-right: 15mm
            margin-bottom: 15mm
            margin-left: 15mm
            encoding: UTF-8